version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt-get update && apt-get install -y unzip
      - curl -O https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip -o terraform_1.5.7_linux_amd64.zip -d /usr/local/bin/
  build:
    commands:
      - terraform init
      - terraform plan
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'