version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing unzip and Terraform...
      - apt-get update && apt-get install -y unzip
      - rm -rf terraform
      - curl -O https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - cd terraform
      - terraform init
      - terraform plan
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'

